import React from 'react';
import ProjectTemplate from '../../components/ProjectTemplate';

export default function IEEEProjects() {
  const projects = [
    { id: 1, title: 'Deepfake Detection using CNN-RNN Hybrid Model', category: 'IEEE', description: 'Identifies manipulated video/audio content by combining spatial and temporal feature analysis to detect deepfakes with higher accuracy than single-model approaches.', tech: 'CNN, LSTM/RNN, TensorFlow, OpenCV, FaceForensics++ Dataset', projectLevel: 'Major', img: 'IEEE' },
    { id: 2, title: 'Hybrid Deep Learning Model for Brain Tumor Classification', category: 'IEEE', description: 'Combines CNN with transfer learning architectures to classify MRI brain scans into tumor types with comparative benchmarking.', tech: 'CNN, VGG16/ResNet, Transfer Learning, Keras, BraTS Dataset', projectLevel: 'Major', img: 'IEEE' },
    { id: 3, title: 'Explainable AI for Diabetic Retinopathy Detection', category: 'IEEE', description: 'Detects diabetic retinopathy stages from retinal images while using Grad-CAM to visualize and explain model decisions.', tech: 'CNN, Grad-CAM, TensorFlow, EfficientNet, APTOS Dataset', projectLevel: 'Major', img: 'IEEE' },
    { id: 4, title: 'Federated Learning-Based Intrusion Detection System', category: 'IEEE', description: 'Detects network intrusions across distributed nodes without centralizing sensitive data, preserving privacy while maintaining detection accuracy.', tech: 'Federated Learning, TensorFlow Federated, Random Forest, NSL-KDD Dataset', projectLevel: 'Major', img: 'IEEE' },
    { id: 5, title: 'Multilingual Fake News Detection using Transformer Models', category: 'IEEE', description: 'Detects fake news across multiple languages using multilingual transformer embeddings and comparative analysis with traditional ML.', tech: 'mBERT, XLM-RoBERTa, NLP, Scikit-learn, Python', projectLevel: 'Major', img: 'IEEE' },
    { id: 6, title: 'Hybrid CNN-LSTM Model for Human Activity Recognition', category: 'IEEE', description: 'Recognizes complex human activities from wearable sensor data using a hybrid spatial-temporal deep learning architecture.', tech: 'CNN, LSTM, Keras, UCI HAR Dataset, Python', projectLevel: 'Major', img: 'IEEE' },
    { id: 7, title: 'Ensemble Learning-Based Credit Risk Prediction Model', category: 'IEEE', description: 'Combines multiple ensemble techniques (bagging, boosting, stacking) to improve credit default prediction accuracy with comparative evaluation.', tech: 'XGBoost, LightGBM, Random Forest, Stacking Ensemble, Scikit-learn', projectLevel: 'Major', img: 'IEEE' },
    { id: 8, title: 'Attention-Based Neural Machine Translation System', category: 'IEEE', description: 'Translates text between languages using attention mechanisms and transformer architecture, benchmarked against traditional seq2seq models.', tech: 'Transformers, Attention Mechanism, PyTorch, BLEU Score Evaluation', projectLevel: 'Major', img: 'IEEE' },
    { id: 9, title: 'Graph Neural Network-Based Recommendation System', category: 'IEEE', description: 'Models user-item interactions as a graph to generate more accurate recommendations compared to traditional collaborative filtering.', tech: 'Graph Neural Networks (GNN), PyTorch Geometric, Python, MovieLens Dataset', projectLevel: 'Major', img: 'IEEE' },
    { id: 10, title: 'Hybrid Model for Crop and Weed Classification using Drone Imagery', category: 'IEEE', description: 'Classifies crops and weeds from UAV-captured images using a hybrid CNN model for precision agriculture applications.', tech: 'CNN, YOLOv8, Drone/UAV Imagery, TensorFlow', projectLevel: 'Major', img: 'IEEE' },
    { id: 11, title: 'Transfer Learning-Based Skin Cancer Classification', category: 'IEEE', description: 'Classifies skin lesion images into cancer types using pretrained deep learning models with performance comparison across architectures.', tech: 'CNN, ResNet50, InceptionV3, Transfer Learning, ISIC Dataset', projectLevel: 'Major', img: 'IEEE' },
    { id: 12, title: 'Hate Speech Detection using BERT-Based Deep Learning', category: 'IEEE', description: 'Detects hate speech and offensive content on social media using contextual embeddings and compares performance with classical NLP models.', tech: 'BERT, NLP, TensorFlow, HuggingFace Transformers', projectLevel: 'Major', img: 'IEEE' },
    { id: 13, title: 'Adversarial Attack Detection in Deep Learning Models', category: 'IEEE', description: 'Identifies adversarial perturbations designed to fool image classification models and proposes defense mechanisms.', tech: 'CNN, Adversarial Training, TensorFlow, FGSM/PGD Attacks', projectLevel: 'Major', img: 'IEEE' },
    { id: 14, title: 'Multi-Modal Emotion Recognition using Audio and Text', category: 'IEEE', description: 'Combines speech and text features to recognize human emotions with higher accuracy than single-modality models.', tech: 'CNN, LSTM, Librosa, NLP, Multimodal Fusion', projectLevel: 'Major', img: 'IEEE' },
    { id: 15, title: 'Time-Series Anomaly Detection using Autoencoders', category: 'IEEE', description: 'Detects anomalies in sensor/IoT time-series data using unsupervised deep learning with reconstruction error analysis.', tech: 'Autoencoders, LSTM, TensorFlow, Python', projectLevel: 'Major', img: 'IEEE' },
    { id: 16, title: 'Hybrid Recommendation System using Deep Learning and Collaborative Filtering', category: 'IEEE', description: 'Combines neural collaborative filtering with content-based features to improve recommendation accuracy and address cold-start problems.', tech: 'Neural Collaborative Filtering, TensorFlow, Matrix Factorization, Python', projectLevel: 'Major', img: 'IEEE' },
    { id: 17, title: 'Real-Time Object Detection for Autonomous Vehicles', category: 'IEEE', description: 'Detects pedestrians, vehicles, and obstacles in real-time video for self-driving car applications with speed-accuracy tradeoff analysis.', tech: 'YOLOv8, OpenCV, PyTorch, KITTI Dataset', projectLevel: 'Major', img: 'IEEE' },
    { id: 18, title: 'Deep Learning-Based COVID-19 Detection from Chest X-Rays', category: 'IEEE', description: 'Classifies chest X-ray images to detect COVID-19 using CNN architectures with comparative study across multiple models.', tech: 'CNN, VGG19, TensorFlow, COVID-19 Radiography Dataset', projectLevel: 'Major', img: 'IEEE' },
    { id: 19, title: 'Blockchain-Integrated Machine Learning for Secure Data Sharing', category: 'IEEE', description: 'Combines blockchain with ML models to enable secure and verifiable data sharing for healthcare or IoT applications.', tech: 'Blockchain, Machine Learning, Python, Smart Contracts', projectLevel: 'Major', img: 'IEEE' },
    { id: 20, title: 'Speech-to-Text Conversion using Deep Learning for Regional Languages', category: 'IEEE', description: 'Converts spoken regional language audio into text using deep learning-based speech recognition models.', tech: 'RNN, CTC Loss, TensorFlow, Librosa', projectLevel: 'Major', img: 'IEEE' },
    { id: 21, title: 'Predictive Maintenance using IoT Sensor Data and Machine Learning', category: 'IEEE', description: 'Predicts equipment failure in industrial settings using sensor data patterns and time-series forecasting.', tech: 'LSTM, Random Forest, IoT Sensor Data, Python', projectLevel: 'Major', img: 'IEEE' },
    { id: 22, title: 'GAN-Based Image Synthesis for Data Augmentation', category: 'IEEE', description: 'Generates synthetic training images using Generative Adversarial Networks to improve model performance on limited datasets.', tech: 'GAN, DCGAN, TensorFlow/PyTorch, Python', projectLevel: 'Major', img: 'IEEE' },
    { id: 23, title: 'Cyberbullying Detection using Deep Learning and Sentiment Analysis', category: 'IEEE', description: 'Detects cyberbullying content on social platforms using deep contextual embeddings combined with sentiment features.', tech: 'BERT, LSTM, NLP, Scikit-learn', projectLevel: 'Major', img: 'IEEE' },
    { id: 24, title: 'Hybrid Model for Parkinson\'s Disease Detection using Voice Analysis', category: 'IEEE', description: 'Detects early signs of Parkinson\'s disease from voice recordings using acoustic feature extraction and hybrid ML models.', tech: 'SVM, Random Forest, Librosa, MFCC Features', projectLevel: 'Major', img: 'IEEE' },
    { id: 25, title: 'Reinforcement Learning-Based Traffic Signal Control System', category: 'IEEE', description: 'Optimizes traffic signal timing using reinforcement learning to reduce congestion, compared against traditional fixed-timing systems.', tech: 'Reinforcement Learning, Q-Learning, Python, SUMO Simulator', projectLevel: 'Major', img: 'IEEE' },
    { id: 26, title: 'Multi-Class Plant Disease Detection using Vision Transformers', category: 'IEEE', description: 'Classifies multiple plant diseases from leaf images using Vision Transformer architecture, benchmarked against CNN models.', tech: 'Vision Transformer (ViT), PyTorch, PlantVillage Dataset', projectLevel: 'Major', img: 'IEEE' },
    { id: 27, title: 'Deep Learning-Based Driver Drowsiness Detection with Alert System', category: 'IEEE', description: 'Detects driver fatigue using facial landmark and eye-closure analysis with real-time alert generation for accident prevention.', tech: 'CNN, Dlib, OpenCV, Facial Landmark Detection', projectLevel: 'Major', img: 'IEEE' },
    { id: 28, title: 'Explainable AI for Loan Default Prediction using SHAP', category: 'IEEE', description: 'Predicts loan defaults using ensemble models while providing feature-level explanations through SHAP values for regulatory transparency.', tech: 'XGBoost, SHAP, Scikit-learn, Pandas', projectLevel: 'Major', img: 'IEEE' },
    { id: 29, title: 'Cross-Lingual Text Summarization using Transformer Models', category: 'IEEE', description: 'Summarizes text content across different languages using transformer-based encoder-decoder architectures.', tech: 'mT5, Transformers, HuggingFace, NLP', projectLevel: 'Major', img: 'IEEE' },
    { id: 30, title: 'Federated Learning for Privacy-Preserving Healthcare Diagnosis', category: 'IEEE', description: 'Trains diagnostic ML models across multiple hospitals without sharing raw patient data, ensuring privacy compliance.', tech: 'Federated Learning, CNN, TensorFlow Federated, Healthcare Imaging Data', projectLevel: 'Major', img: 'IEEE' }
  ];

  return (
    <ProjectTemplate 
      title="IEEE Research Projects"
      description="Implementation of base research papers and advanced engineering system prototypes."
      projects={projects}
      backgroundGradient="linear-gradient(135deg, var(--primary-dark) 0%, #1e40af 100%)"
    />
  );
}
