import React from 'react';
import ProjectTemplate from '../../components/ProjectTemplate';

export default function MLProjects() {
  const projects = [
    // Major ML Projects (30 items)
    { id: 1, title: 'Real-Time Face Mask Detection', category: 'Machine Learning', description: 'Detects whether a person is wearing a mask using live video feed for public safety monitoring.', tech: 'Python, OpenCV, CNN, TensorFlow/Keras, MobileNetV2', projectLevel: 'Major', img: 'ML' },
    { id: 2, title: 'Plant Disease Detection from Leaf Images', category: 'Machine Learning', description: 'Identifies crop diseases from leaf photos to help farmers take early action.', tech: 'CNN, TensorFlow, Keras, Image Augmentation, Flask', projectLevel: 'Major', img: 'ML' },
    { id: 3, title: 'Automatic Number Plate Recognition (ANPR)', category: 'Machine Learning', description: 'Detects and reads vehicle license plates from images/video for toll systems or parking.', tech: 'OpenCV, YOLO, Tesseract OCR, Python', projectLevel: 'Major', img: 'ML' },
    { id: 4, title: 'Credit Card Fraud Detection', category: 'Machine Learning', description: 'Flags fraudulent transactions using anomaly detection on imbalanced datasets.', tech: 'Scikit-learn, XGBoost, SMOTE, Pandas, Random Forest', projectLevel: 'Major', img: 'ML' },
    { id: 5, title: 'Customer Churn Prediction', category: 'Machine Learning', description: 'Predicts which customers are likely to leave a service (telecom/banking).', tech: 'Logistic Regression, XGBoost, Scikit-learn, Power BI', projectLevel: 'Major', img: 'ML' },
    { id: 6, title: 'Heart Disease Prediction System', category: 'Machine Learning', description: 'Predicts risk of heart disease based on patient health parameters.', tech: 'Scikit-learn, Random Forest, SVM, Flask/Streamlit', projectLevel: 'Major', img: 'ML' },
    { id: 7, title: 'Resume Screening and Job Matching System', category: 'Machine Learning', description: 'Automatically ranks resumes against job descriptions using text similarity.', tech: 'NLP, spaCy, TF-IDF/BERT, Cosine Similarity, Python', projectLevel: 'Major', img: 'ML' },
    { id: 8, title: 'AI-Powered Customer Support Chatbot', category: 'Machine Learning', description: 'Handles customer queries using intent recognition and conversational AI.', tech: 'NLTK/spaCy, RASA/Dialogflow, LSTM/Transformers, Flask', projectLevel: 'Major', img: 'ML' },
    { id: 9, title: 'Stock Price Prediction using LSTM', category: 'Machine Learning', description: 'Forecasts future stock prices using historical time-series data.', tech: 'LSTM, Keras, TensorFlow, Pandas, Matplotlib', projectLevel: 'Major', img: 'ML' },
    { id: 10, title: 'Sales Forecasting for Retail', category: 'Machine Learning', description: 'Predicts future sales trends to optimize inventory and supply chain.', tech: 'ARIMA, Prophet, XGBoost, Pandas, Power BI', projectLevel: 'Major', img: 'ML' },
    { id: 11, title: 'Intrusion Detection System', category: 'Machine Learning', description: 'Detects malicious network traffic/attacks in real-time.', tech: 'Random Forest, SVM, NSL-KDD Dataset, Scikit-learn', projectLevel: 'Major', img: 'ML' },
    { id: 12, title: 'Phishing Website Detection', category: 'Machine Learning', description: 'Classifies URLs as legitimate or phishing using feature-based ML.', tech: 'Random Forest, Decision Trees, Feature Engineering, Flask', projectLevel: 'Major', img: 'ML' },
    { id: 13, title: 'Fake News Detection System', category: 'Machine Learning', description: 'Classifies news articles as real or fake using NLP techniques.', tech: 'NLP, TF-IDF, Naive Bayes/LSTM, Scikit-learn', projectLevel: 'Major', img: 'ML' },
    { id: 14, title: 'Sentiment Analysis on Social Media Data', category: 'Machine Learning', description: 'Analyzes public sentiment on Twitter/Reddit for brands or events.', tech: 'NLP, BERT, Tweepy API, VADER, Python', projectLevel: 'Major', img: 'ML' },
    { id: 15, title: 'Movie/Product Recommendation System', category: 'Machine Learning', description: 'Suggests items to users based on collaborative and content-based filtering.', tech: 'Surprise Library, Cosine Similarity, Matrix Factorization (SVD), Pandas', projectLevel: 'Major', img: 'ML' },
    { id: 16, title: 'Object Detection for Surveillance Systems', category: 'Machine Learning', description: 'Detects and tracks objects/people in CCTV footage in real time.', tech: 'YOLOv8, OpenCV, PyTorch, Deep SORT', projectLevel: 'Major', img: 'ML' },
    { id: 17, title: 'Speech Emotion Recognition', category: 'Machine Learning', description: 'Detects human emotions (happy, sad, angry) from voice recordings.', tech: 'Librosa, CNN, MFCC Feature Extraction, TensorFlow', projectLevel: 'Major', img: 'ML' },
    { id: 18, title: 'Traffic Sign Recognition System', category: 'Machine Learning', description: 'Classifies traffic signs for use in driver assistance/autonomous vehicles.', tech: 'CNN, GTSRB Dataset, TensorFlow, OpenCV', projectLevel: 'Major', img: 'ML' },
    { id: 19, title: 'Employee Attrition Prediction', category: 'Machine Learning', description: 'Predicts which employees are likely to resign based on HR data.', tech: 'Logistic Regression, Random Forest, Scikit-learn, Power BI', projectLevel: 'Major', img: 'ML' },
    { id: 20, title: 'Human Activity Recognition using Sensor Data', category: 'Machine Learning', description: 'Classifies physical activities (walking, running, sitting) using smartphone sensors.', tech: 'LSTM, CNN, Accelerometer/Gyroscope Data, Keras', projectLevel: 'Major', img: 'ML' },
    { id: 21, title: 'License Plate-Based Vehicle Parking System', category: 'Machine Learning', description: 'Automates parking entry/exit using plate detection and billing.', tech: 'OpenCV, YOLO, Tesseract OCR, Python, MySQL', projectLevel: 'Major', img: 'ML' },
    { id: 22, title: 'AI Resume Builder & Skill Gap Analyzer', category: 'Machine Learning', description: 'Analyzes resumes and suggests skill improvements based on job trends.', tech: 'NLP, BERT, Named Entity Recognition (NER), Flask', projectLevel: 'Major', img: 'ML' },
    { id: 23, title: 'Crop Yield Prediction System', category: 'Machine Learning', description: 'Predicts agricultural yield based on soil, weather, and historical data.', tech: 'Random Forest, XGBoost, Pandas, Weather API Integration', projectLevel: 'Major', img: 'ML' },
    { id: 24, title: 'Real Estate Price Prediction', category: 'Machine Learning', description: 'Predicts property prices based on location, size, and amenities.', tech: 'Linear Regression, XGBoost, Scikit-learn, Streamlit', projectLevel: 'Major', img: 'ML' },
    { id: 25, title: 'Voice-Based Virtual Assistant', category: 'Machine Learning', description: 'Executes tasks (search, reminders, app control) via voice commands.', tech: 'SpeechRecognition, NLP, Python, pyttsx3, Wolfram Alpha API', projectLevel: 'Major', img: 'ML' },
    { id: 26, title: 'Driver Drowsiness Detection System', category: 'Machine Learning', description: 'Monitors driver\'s eyes/face to detect fatigue and prevent accidents.', tech: 'OpenCV, Dlib, CNN, Facial Landmark Detection', projectLevel: 'Major', img: 'ML' },
    { id: 27, title: 'Automated Attendance System using Face Recognition', category: 'Machine Learning', description: 'Marks attendance automatically by recognizing faces via camera.', tech: 'OpenCV, face_recognition library, CNN, SQLite', projectLevel: 'Major', img: 'ML' },
    { id: 28, title: 'AI-Based Personal Finance Tracker & Predictor', category: 'Machine Learning', description: 'Categorizes expenses and predicts future spending patterns.', tech: 'NLP (transaction categorization), Time-Series Forecasting, Pandas', projectLevel: 'Major', img: 'ML' },
    { id: 29, title: 'Cyberbullying Detection on Social Media', category: 'Machine Learning', description: 'Detects abusive/harassing text content across platforms.', tech: 'NLP, LSTM/BERT, TF-IDF, Scikit-learn', projectLevel: 'Major', img: 'ML' },
    { id: 30, title: 'Multilingual Chatbot for Government Services', category: 'Machine Learning', description: 'Provides citizen services info in multiple regional languages.', tech: 'NLP, mBERT/IndicBERT, Rasa, Flask', projectLevel: 'Major', img: 'ML' },

    // Minor ML Projects (30 items)
    { id: 95, title: 'Iris Flower Classification', category: 'Machine Learning', description: 'Classifies iris flowers into species based on petal and sepal measurements — a classic beginner ML dataset.', tech: 'Python, Scikit-learn, Pandas, Matplotlib', projectLevel: 'Minor', img: 'ML' },
    { id: 96, title: 'Titanic Survival Prediction', category: 'Machine Learning', description: 'Predicts passenger survival on the Titanic based on age, class, and other features.', tech: 'Python, Pandas, Scikit-learn, Logistic Regression', projectLevel: 'Minor', img: 'ML' },
    { id: 97, title: 'House Price Prediction using Regression', category: 'Machine Learning', description: 'Predicts housing prices based on area, location, and number of rooms.', tech: 'Linear Regression, Scikit-learn, Pandas, NumPy', projectLevel: 'Minor', img: 'ML' },
    { id: 98, title: 'Diabetes Prediction using Machine Learning', category: 'Machine Learning', description: 'Predicts likelihood of diabetes based on patient health metrics.', tech: 'Scikit-learn, Logistic Regression, Pandas, Seaborn', projectLevel: 'Minor', img: 'ML' },
    { id: 99, title: 'Spam Email Classification', category: 'Machine Learning', description: 'Classifies emails as spam or not spam using text features.', tech: 'NLP, Naive Bayes, Scikit-learn, CountVectorizer', projectLevel: 'Minor', img: 'ML' },
    { id: 100, title: 'Sentiment Analysis of Product Reviews', category: 'Machine Learning', description: 'Determines whether product reviews are positive or negative.', tech: 'NLP, TF-IDF, Scikit-learn, NLTK', projectLevel: 'Minor', img: 'ML' },
    { id: 101, title: 'Handwritten Digit Recognition', category: 'Machine Learning', description: 'Recognizes handwritten digits (0-9) using the MNIST dataset.', tech: 'CNN, TensorFlow/Keras, MNIST Dataset', projectLevel: 'Minor', img: 'ML' },
    { id: 102, title: 'Twitter Sentiment Analysis', category: 'Machine Learning', description: 'Analyzes tweets to determine public sentiment on a topic or brand.', tech: 'NLP, Tweepy API, VADER, Python', projectLevel: 'Minor', img: 'ML' },
    { id: 103, title: 'Customer Segmentation using K-Means Clustering', category: 'Machine Learning', description: 'Groups customers into segments based on purchasing behavior.', tech: 'K-Means Clustering, Scikit-learn, Pandas, Matplotlib', projectLevel: 'Minor', img: 'ML' },
    { id: 104, title: 'Loan Approval Prediction System', category: 'Machine Learning', description: 'Predicts whether a loan application will be approved based on applicant details.', tech: 'Logistic Regression, Random Forest, Scikit-learn, Pandas', projectLevel: 'Minor', img: 'ML' },
    { id: 105, title: 'Fake News Detection (Basic Model)', category: 'Machine Learning', description: 'Classifies news headlines/articles as real or fake.', tech: 'NLP, TF-IDF, Naive Bayes, Scikit-learn', projectLevel: 'Minor', img: 'ML' },
    { id: 106, title: 'Wine Quality Prediction', category: 'Machine Learning', description: 'Predicts the quality rating of wine based on chemical properties.', tech: 'Random Forest, Scikit-learn, Pandas, NumPy', projectLevel: 'Minor', img: 'ML' },
    { id: 107, title: 'Movie Recommendation System (Content-Based)', category: 'Machine Learning', description: 'Recommends movies to users based on genre and content similarity.', tech: 'Cosine Similarity, TF-IDF, Pandas, Scikit-learn', projectLevel: 'Minor', img: 'ML' },
    { id: 108, title: 'Email Spam Filter using Naive Bayes', category: 'Machine Learning', description: 'Filters spam emails using probabilistic text classification.', tech: 'Naive Bayes, NLP, Scikit-learn, Pandas', projectLevel: 'Minor', img: 'ML' },
    { id: 109, title: 'Student Performance Prediction', category: 'Machine Learning', description: 'Predicts student exam scores or pass/fail outcomes based on study habits and attendance.', tech: 'Linear Regression, Scikit-learn, Pandas, Matplotlib', projectLevel: 'Minor', img: 'ML' },
    { id: 110, title: 'Air Quality Index Prediction', category: 'Machine Learning', description: 'Predicts AQI levels based on pollutant concentration data.', tech: 'Regression Models, Scikit-learn, Pandas, NumPy', projectLevel: 'Minor', img: 'ML' },
    { id: 111, title: 'Weather Prediction using Machine Learning', category: 'Machine Learning', description: 'Predicts temperature or rainfall based on historical weather data.', tech: 'Random Forest, Scikit-learn, Pandas, Matplotlib', projectLevel: 'Minor', img: 'ML' },
    { id: 112, title: 'Employee Salary Prediction', category: 'Machine Learning', description: 'Predicts employee salary based on experience, role, and education.', tech: 'Linear Regression, Scikit-learn, Pandas', projectLevel: 'Minor', img: 'ML' },
    { id: 113, title: 'Breast Cancer Detection (Basic Model)', category: 'Machine Learning', description: 'Classifies tumors as benign or malignant using diagnostic features.', tech: 'SVM, Logistic Regression, Scikit-learn, Pandas', projectLevel: 'Minor', img: 'ML' },
    { id: 114, title: 'Fruit Classification using Image Processing', category: 'Machine Learning', description: 'Classifies different types of fruits from images.', tech: 'CNN, TensorFlow/Keras, OpenCV', projectLevel: 'Minor', img: 'ML' },
    { id: 115, title: 'Book Recommendation System', category: 'Machine Learning', description: 'Recommends books to users based on ratings and preferences.', tech: 'Collaborative Filtering, Pandas, Scikit-learn', projectLevel: 'Minor', img: 'ML' },
    { id: 116, title: 'Music Genre Classification', category: 'Machine Learning', description: 'Classifies music tracks into genres based on audio features.', tech: 'Librosa, CNN, TensorFlow, MFCC Feature Extraction', projectLevel: 'Minor', img: 'ML' },
    { id: 117, title: 'Language Detection using Machine Learning', category: 'Machine Learning', description: 'Detects the language of a given text input.', tech: 'NLP, Naive Bayes, Scikit-learn, langdetect', projectLevel: 'Minor', img: 'ML' },
    { id: 118, title: 'Emotion Detection from Text', category: 'Machine Learning', description: 'Classifies text into emotions like happy, sad, angry, or neutral.', tech: 'NLP, LSTM, TensorFlow, Scikit-learn', projectLevel: 'Minor', img: 'ML' },
    { id: 119, title: 'Credit Card Fraud Detection (Basic Model)', category: 'Machine Learning', description: 'Identifies fraudulent transactions using a small labeled dataset.', tech: 'Logistic Regression, Scikit-learn, Pandas', projectLevel: 'Minor', img: 'ML' },
    { id: 120, title: 'Face Detection using OpenCV', category: 'Machine Learning', description: 'Detects human faces in images or webcam feed in real time.', tech: 'OpenCV, Haar Cascades, Python', projectLevel: 'Minor', img: 'ML' },
    { id: 121, title: 'Calories Burnt Prediction', category: 'Machine Learning', description: 'Predicts calories burnt during exercise based on activity and biometric data.', tech: 'Linear Regression, XGBoost, Scikit-learn, Pandas', projectLevel: 'Minor', img: 'ML' },
    { id: 122, title: 'Online Payment Fraud Detection', category: 'Machine Learning', description: 'Identifies fraudulent online payment transactions using classification models.', tech: 'Random Forest, Scikit-learn, Pandas, NumPy', projectLevel: 'Minor', img: 'ML' },
    { id: 123, title: 'Text Summarization (Basic Extractive Model)', category: 'Machine Learning', description: 'Generates a short summary from a longer piece of text.', tech: 'NLP, NLTK, Gensim, TF-IDF', projectLevel: 'Minor', img: 'ML' },
    { id: 124, title: 'Chatbot using Rule-Based NLP', category: 'Machine Learning', description: 'Responds to user queries using predefined rules and pattern matching.', tech: 'NLTK, Python, Regular Expressions', projectLevel: 'Minor', img: 'ML' }
  ];

  return (
    <ProjectTemplate 
      title="Machine Learning Projects"
      description="Supervised and unsupervised models for classification, regression, and data clustering."
      projects={projects}
      backgroundGradient="linear-gradient(135deg, var(--primary-dark) 0%, #4f46e5 100%)"
    />
  );
}
